#!/usr/bin/env python3
"""Generates src/spirv_opcodes.h from the Khronos SPIR-V grammar.

The opcode numbers and enumerant values are not worth keeping in anyone's head:
a wrong constant produces a module that fails validation, or worse, one that
validates and computes the wrong thing. So they are generated from the same
grammar SPIRV-Tools uses.

Usage:
    python3 scripts/gen_spirv_opcodes.py <spirv.core.grammar.json> <out.h>

The grammar is vendored by SPIRV-Headers at
include/spirv/unified1/spirv.core.grammar.json.
"""

import json
import sys


import re

IDENTIFIER = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def sanitise(name, prefix=""):
    """Makes a grammar name usable as a C++ enumerant.

    Vendor names carry characters that are not valid in an identifier, and
    some categories use names that start with a digit (Dim's 1D, 2D, 3D). Those
    are rewritten with the category name as a prefix, which is both valid and
    distinguishable, rather than collapsed onto one placeholder."""
    if IDENTIFIER.match(name):
        return name
    cleaned = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if not cleaned:
        return prefix + "Value"
    return prefix + cleaned


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)

    grammar = json.load(open(sys.argv[1]))
    out_path = sys.argv[2]

    instructions = grammar["instructions"]

    # The grammar lists operands before the result, while C wants the result
    # type first, so the header records only the opcode number and the emitter
    # supplies operands positionally.
    lines = []
    lines.append("/* Generated by scripts/gen_spirv_opcodes.py. Do not edit by hand. */")
    lines.append("")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <cstdint>")
    lines.append("")
    lines.append("namespace mslc {")
    lines.append("namespace spirv {")
    lines.append("")
    lines.append("enum Opcode : uint16_t {")

    for instruction in sorted(instructions, key=lambda i: i["opcode"]):
        lines.append("\t%s = %d," % (instruction["opname"], instruction["opcode"]))

    lines.append("};")
    lines.append("")

    # Enumerants the emitter needs, with the categories named in the grammar.
    # Kind names in the grammar, not the prose names used in the spec.
    wanted = {
        "StorageClass": "StorageClass",
        "Decoration": "Decoration",
        "BuiltIn": "BuiltIn",
        "Capability": "Capability",
        "ExecutionModel": "ExecutionModel",
        "ExecutionMode": "ExecutionMode",
        "FunctionControl": "FunctionControl",
        "SelectionControl": "SelectionControl",
        "LoopControl": "LoopControl",
        "MemoryAccess": "MemoryAccess",
        "AddressingModel": "AddressingModel",
        "MemoryModel": "MemoryModel",
        "Dim": "Dim",
        "ImageFormat": "ImageFormat",
        "SourceLanguage": "SourceLanguage",
    }

    # operand_kinds is a list, so index it by name before looking anything up.
    kinds_by_name = {k["kind"]: k for k in grammar["operand_kinds"]}

    for kind_name, enum_name in wanted.items():
        category = kinds_by_name.get(kind_name)
        if category is None:
            continue

        enumerants = category.get("enumerants", [])
        if not enumerants:
            continue

        # A mask category spells its values as hex literals ("0x0004"), while an
        # enumeration category uses a plain number. Both are emitted verbatim so
        # the header reads like the grammar, and so a mask keeps the None = 0 the
        # emitter needs by name.
        def render(enumerant):
            value = enumerant["value"]
            return value if isinstance(value, str) else str(value)

        # Sorting has to be numeric, not lexical. The hex literals are not
        # uniformly padded, so "0x20000" sorts after "0x10000000" as text and
        # the enum comes out in the wrong order.
        def order(enumerant):
            value = enumerant["value"]
            return int(value, 16) if isinstance(value, str) else value

        # Each category becomes its own namespace rather than a bare enum,
        # because the specification reuses names across categories: Uniform is
        # both a storage class and a decoration, Kernel is both an execution
        # model and a memory model. Namespacing them keeps the natural
        # spirv::StorageClass::Uniform spelling without redeclaration errors.
        lines.append("namespace %s {" % enum_name)
        lines.append("\tenum Value : uint32_t {")
        for enumerant in sorted(enumerants, key=order):
            if "aliases" in enumerant and enumerant["value"] == 0:
                # Skip the leading "None = 0" placeholder several categories
                # carry, since the emitter never references it.
                continue
            comment = ""
            if enumerant.get("capabilities"):
                comment = "  // requires %s" % ", ".join(enumerant["capabilities"])
            lines.append("\t\t%s = %s,%s" % (sanitise(enumerant["enumerant"], enum_name),
                render(enumerant), comment))
        lines.append("\t};")
        lines.append("}")
        lines.append("")
        # A type alias, so callers can name the enum type without writing
        # Value and so the category name stays usable as spirv::StorageClass::X.
        lines.append("using %sValue = %s::Value;" % (enum_name, enum_name))
        lines.append("")

    lines.append("}")
    lines.append("}")
    lines.append("")

    with open(out_path, "w") as handle:
        handle.write("\n".join(lines))

    print("wrote %s (%d opcodes)" % (out_path, len(instructions)))


if __name__ == "__main__":
    main()
