#pragma once

#include "spirv_opcodes.h"

#include <cstdint>
#include <map>
#include <string>
#include <vector>

namespace mslc {
namespace spirv {

// Opcode numbers and enumerant values come from spirv_opcodes.h, which is
// generated by scripts/gen_spirv_opcodes.py from the Khronos grammar. Nothing
// numeric is written by hand here: a wrong opcode produces a module that fails
// validation, or one that validates and computes the wrong thing.

using Id = uint32_t;
constexpr Id InvalidId = 0;

// SPIR-V logical layout, in the order the binary requires. Emitting into the
// right section as work happens means finalize() only has to concatenate.
enum class Section {
	Capabilities,
	Extensions,
	ExtInstImports,
	MemoryModel,
	EntryPoints,
	ExecutionModes,
	Debug,
	Annotations,
	TypesGlobals,
	Functions,
	Literals,

	// Not a real section: the sentinel sectionForOpcode returns for an opcode
	// that goes wherever the caller is currently emitting.
	Invalid,
};

struct Instruction {
	uint16_t opcode = 0;
	std::vector<uint32_t> words;
};

// Binary SPIR-V builder.
//
// Ids are allocated as work is discovered rather than when an instruction is
// emitted, so an id can be referenced before the thing it names is declared.
class Builder {
	Id _nextId = 1;

	std::map<Section, std::vector<Instruction>> _sections;
	std::vector<Instruction> _literals;

	// Literal pool, keyed by the word sequence, so an identical literal is
	// stored once.
	std::map<std::vector<uint32_t>, Id> _literalIds;

	// The SPIR-V type of every value id handed out. Tracking it here rather
	// than threading an out-parameter through every expression means the
	// emitter never has to re-derive a type it already knew, and it removes
	// the confusion between a pointer's own type and its pointee.
	std::map<Id, Id> _valueTypes;

	Section _currentSection = Section::TypesGlobals;

public:
	Id nextId() { return _nextId++; }

	// Sets the section subsequent instructions land in. Types and global
	// variables go to TypesGlobals; instruction bodies go to Functions, which
	// the emitter switches between.
	void setSection(Section section) { _currentSection = section; }
	Section section() const { return _currentSection; }

	// Emits an instruction with the given opcode and operand words. The word
	// count in the first header word is filled in by finalize(), so callers
	// pass only operands.
	Id emit(uint16_t opcode, std::vector<uint32_t> operands = {});

	// Emits an instruction whose first operand is the result type, and records
	// the value so typeOf() can answer for it later. This is the form almost
	// every value-producing instruction takes.
	Id emitTyped(uint16_t opcode, Id resultType, std::vector<uint32_t> operands);

	// Emits a declaration that has no result type: the grammar's first operand
	// is IdResult, so the result id goes first and the caller supplies the rest.
	// OpTypeVoid, OpTypeFloat, OpTypeStruct, OpTypePointer, OpTypeFunction,
	// OpLabel and OpExtInstImport are this form. Nothing is recorded in the
	// value table, because a type, a label or a set id is not a value.
	//
	// Anything the grammar gives IdResultType, which includes every OpConstant
	// form, is emitDeclTyped instead. Prepending the id ahead of a result type
	// the caller already passed emits the two swapped, which reads as the
	// result type defining the result id.
	Id emitDecl(uint16_t opcode, std::vector<uint32_t> operands = {});

	// A declaration that also carries a result type, laid out as
	// [result type, result id, operands...]. OpVariable, OpFunction and the
	// OpConstant family are these.
	Id emitDeclTyped(uint16_t opcode, Id resultType, std::vector<uint32_t> operands);

	// As emitDeclTyped, but with a result id the caller already allocated. An
	// OpFunction needs this: the entry point names the function's id, so the two
	// have to be the same value rather than two separately allocated ones.
	void emitDeclTypedAt(uint16_t opcode, Id resultType, Id resultId,
		std::vector<uint32_t> operands);

	// The recorded type of a value, or InvalidId when the id is unknown.
	Id typeOf(Id value) const;

	// The section an opcode belongs in, given where the caller is emitting. An
	// opcode with a required section ignores the current one, so a constant
	// emitted from inside a function body still lands in the types block.
	Section pickSection(uint16_t opcode) const;

	// Records a type for an id that was not produced by an instruction, such as
	// a function or a label.
	void setType(Id value, Id type);

	// Emits a NUL-terminated string literal and returns its id, reusing an
	// identical literal if one already exists.
	Id stringLiteral(const std::string& text);

	// Packs a string into SPIR-V literal words and appends them. Instructions
	// such as OpEntryPoint and OpName take the name inline rather than by id,
	// so they need the words rather than a literal reference.
	static void appendString(std::vector<uint32_t>& words, const std::string& text);

	// Serialises to a SPIR-V module. Returns false when no entry point was
	// emitted, since such a module is not loadable.
	bool finalize(std::vector<uint8_t>& out) const;

	bool hasEntryPoint() const { return !_sections.at(Section::EntryPoints).empty(); }
};

// SPIR-V serial version emitted.
//
// 1.3 is the floor, not a preference: the StorageBuffer storage class and
// OpTypeRuntimeArray were both introduced in 1.3, and lowering a Metal device
// pointer to a StorageBuffer descriptor needs both. Emitting 1.0 and using them
// produces a module spirv-val rejects.
constexpr uint32_t kSpirvVersion = 0x00010300;

// SPIR-V magic number, "SPV" in little-endian words.
constexpr uint32_t kSpirvMagic = 0x07230203;

}
}
