// EXPECT: valid
//
// A || whose right operand is an && expression, 200 deep: each level adds two nested
// selection constructs. A middling case that stays quick to validate.
// Each right operand of && or || is a selection construct in the module, and spirv-val
// rejects a module nested 1023 deep, so mslc limits the nesting it emits to 1000.
kernel void logical_or_nested_and_right_operand_200_deep_valid(device uint *out [[buffer(0)]], constant int *v [[buffer(1)]], uint i [[thread_position_in_grid]])
{
    bool a = v[i] > 0;
    bool b2 = v[i] > 1;
    uint c = 0;
    a = a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a || b2 && (a))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
    out[i] = c;
}
